### ISSUE TITLE
Source for Solanum

### ISSUE THREAD

**Issue by henk84** [jneubrand/solanum-config#1]
Hi

Sorry for contacting you this way, I did not find any other.
Is the source for the pebble app "Solanum" itself (i.e. not the config page) available anywhere?
If not: can you please consider publishing it?

Thank you

henk

**Comment by jneubrand** [comment]
I really wish it were! Unfortunately, I lost the source due to a faulty backup a few years ago. You're free to decompile and use it however you want, though :)
